# Generated by Django 3.0.3 on 2020-04-05 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iqama_number', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(blank=True, max_length=30)),
                ('fourth_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('joining_date', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('current_application', models.CharField(blank=True, max_length=50)),
                ('previous_application', models.CharField(blank=True, max_length=50)),
                ('iqama_expiry_date', models.DateField()),
                ('driver_license_expiry_date', models.DateField()),
                ('sponsor_name', models.CharField(max_length=100)),
                ('knows_aout_us', models.CharField(blank=True, max_length=200)),
                ('car_type', models.CharField(max_length=30)),
                ('car_plate_number', models.CharField(max_length=30)),
                ('car_color', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
